package com.sparktech.motorx.entity;

public enum LogActionType {
    LOGIN,
    REGISTER,
    LOGOUT,
    VERIFY_2FA,
    REFRESH_TOKEN,
    PASSWORD_RESET_REQUEST,
    PASSWORD_RESET_CONFIRM,
    UPDATE_USER_PROFILE,
    SCHEDULE_APPOINTMENT,
    CANCEL_APPOINTMENT,
    CREATE_SPARE,
    UPDATE_SPARE,
    UPDATE_SPARE_PURCHASE_PRICE,
    DELETE_SPARE,
    REGISTER_PURCHASE,
    REGISTER_SALE,
    INITIATE_RECEPTION,
    CONFIRM_RECEPTION,
    CREATE_NOTIFICATION,
    READ_NOTIFICATION,
    READ_ALL_NOTIFICATIONS,
    CREATE_SERVICE_ORDER,
    ADD_ORDER_PROCEDURE,
    UPDATE_ORDER_PROCEDURE,
    ADD_ORDER_SPARE,
    COMPLETE_SERVICE_ORDER
}

